-- Database: GLOBALPLA Metadata version: 2 Exported: Apr 18, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6665_JOB_RPT" USING 'GCG_6665_JOB_RPT.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "ORDER_NO" CHAR(7),
 "SERIAL" BIGINT,
 "DESCRIPTION" CHAR(150),
 "MODEL" CHAR(20),
 "NAME_CUSTOMER" CHAR(255),
 "DATE_DUE" DATE,
 "UNITS_PRESSURE" CHAR(3),
 "OP_LOW" INTEGER,
 "OP_HIGH" INTEGER,
 "OP_MAX" INTEGER,
 "PART" CHAR(20),
 "SIZE_CYL" CHAR(25),
 "SIZE_LUBE" CHAR(10),
 "FOLLOW_DOWN" BIT NOT NULL,
 "SHOP_ASSY_BP" CHAR(50),
 "SHOP_ASSY_BY" CHAR(3),
 "RELEASED_BY" CHAR(3),
 "DATE_RELEASED" DATE,
 "PREASSYINSTR" BIT NOT NULL,
 "PREASSYDWG" CHAR(30),
 "POSTASSYINSTR" BIT NOT NULL,
 "POSTASSYDWG" CHAR(30),
 "BRACKET" CHAR(20),
 "ADAPTER" CHAR(20),
 "NESTS" CHAR(50),
 "TEST_PRESSURE" CHAR(10),
 "TEST_DIA" CHAR(10),
 "PADS_WEAR" CHAR(30),
 "NOTES_MISC" LONGVARCHAR,
 "TAG_CUST" BIT NOT NULL,
 "NAME_CUST_TAG" CHAR(17),
 "NUM_CUST_TAG" CHAR(19),
 "DATE_CUST_TAG" DATE,
 "QTY_TAG" INTEGER,
 "PRESSURE_CYCLE" INTEGER,
 "FD_ENHANCED" BIT NOT NULL,
 "ORIG_REWORK" INTEGER );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
