-- Database: GLOBALPLA Metadata version: 2 Exported: Mar 30, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6665_JOB_RPT_TPT" USING 'GCG_6665_JOB_RPT_TPT.mkd' PAGESIZE=4096 (
 "DESCRIPTION" CHAR(150),
 "MODEL" CHAR(20),
 "UNITS_PRESSURE" CHAR(3),
 "OP_LOW" CHAR(50),
 "OP_HIGH" CHAR(50),
 "OP_MAX" CHAR(50),
 "PART" CHAR(20),
 "SIZE_CYL" CHAR(25),
 "SIZE_LUBE" CHAR(10),
 "FOLLOW_DOWN" BIT NOT NULL,
 "PREASSYINSTR" BIT NOT NULL,
 "PREASSYDWG" CHAR(30),
 "POSTASSYINSTR" BIT NOT NULL,
 "POSTASSYDWG" CHAR(30),
 "BRACKET" CHAR(20),
 "ADAPTER" CHAR(20),
 "NESTS" CHAR(50),
 "TEST_PRESSURE" CHAR(10),
 "TEST_DIA" CHAR(10),
 "PADS_WEAR" CHAR(30),
 "NOTES_MISC" LONGVARCHAR,
 "QTY_TAG" INTEGER,
 "FD_ENHANCED" BIT NOT NULL,
 "CYCLE_PRESSURE" INTEGER,
 "SHOP_ASSY_BP" CHAR(50),
 "SHOP_ASSY_BY" CHAR(8) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
